sonar.projectKey=scamshield-pipeline-app
sonar.projectName=ScamShield Pipeline App

sonar.sources=app.js,server.js,public
sonar.tests=tests
sonar.test.inclusions=tests/**/*.js

sonar.exclusions=node_modules/**,coverage/**
sonar.coverage.exclusions=server.js,public/script.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8